### ISSUE TITLE
missing class or uppercase package name (`org.apache.hadoop.fs.FSDataOutputStream')

### ISSUE THREAD

**Issue by muthu1086** [avishai-ish-shalom/logstash-hdfs#5]
Had struck with the same issue. Had set the CLASSPATH with all jars and Config with export CLASSPATH=$(find /opt/hadoop-2.3.0/ -name '*.jar' | tr '\n' ':'):/opt/hadoop-2.3.0/etc/hadoop/:/opt/logstash-1.1.7-monolithic.jar and got below error Any Help

./logstash -f ../hdfstest.conf

Using milestone 2 input plugin 'file'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
+---------------------------------------------------------+
| An unexpected error occurred. This is probably a bug. |
| You can find help with this problem in a few places: |
| |
| \* chat: #logstash IRC channel on freenode irc. |
| IRC via the web: http://goo.gl/TI4Ro |
| \* email: logstash-users@googlegroups.com |
| \* bug system: https://logstash.jira.com/ |
| |
+---------------------------------------------------------+
The error reported is:
missing class or uppercase package name (`org.apache.hadoop.fs.FSDataOutputStream')

**Comment by langke93** [comment]
Classpath setting hadoop jar packages need to exclude the jars of name contains "sources"
find ../hadoop/hadoop -type f -name '*.jar'|grep -v sources

**Comment by avishai-ish-shalom** [comment]
10x
