### ISSUE TITLE
what this plugin does?

### ISSUE THREAD

**Issue by OhadR** [avishai-ish-shalom/logstash-hdfs#9]
i think you should explain better in the README what is the purpose of this plugin. can it be also an input for HDFS?

thanks.

**Comment by avishai-ish-shalom** [comment]
The plugin is output only. I'll clarify in the readme.
It should be easy to add input functionality btw

**Comment by OhadR** [comment]
thanks.
I saw solutions like http://www.paluch.biz/blog/95-logging-hadoop-messages-into-logstash-using-logstash-gelf.html which is basically hdfs-input for logstash. it seems to be complicated (maybe because  it is based on GELF, graylog...) yours seems to be much simpler! :)

**Comment by avishai-ish-shalom** [comment]
The link you are referring to is NOT about reading hdfs files but rather
hadoop daemons loggers messages. Hadoop daemons use log4j and can be easily
configured with logstash just like any other java app.

**Comment by OhadR** [comment]
what I actually need is to read logs of hadoop-tasks. should I use your
plugin (logstash-hdfs <https://github.com/avishai-ish-shalom/logstash-hdfs>)
ot the link I sent you
<http://www.paluch.biz/blog/95-logging-hadoop-messages-into-logstash-using-logstash-gelf.html>is
better for this usecase?

thanks!
Ohad

_______________________________
Ohad Redlich [image: linked-in with me]
<http://il.linkedin.com/in/ohadredlich/>[image: Join my Facebook Page]
<https://www.facebook.com/ohadr.photography>  <https://github.com/OhadR>
<http://stackoverflow.com/users/421642/ohadr>

**Comment by avishai-ish-shalom** [comment]
If you are using YARN then task logs (stderr, stdout, etc) are saved to local files on nodes then optionally aggregated and saved to HDFS after the job has finished. If you don't mind waiting for jobs to finish you can collect the logs from HDFS - this plugin is output only and doesn't support it, but writing an HDFS input should be easy. If you do mind waiting for jobs to finish (you want near realtime logs) then you can either collect them from local filesystem using local logstash agent/forwarder on each node or use log4j with some remote appender (gelf, SocketAppender, etc.) on the task itself. you may have to modify the task package btw.

**Comment by OhadR** [comment]
Thanks for your great answer!
Much appreciated!
Ohad
